### ISSUE TITLE
[Feature Request] Add Cropping Operation to the Image Editing Feature

### ISSUE THREAD

**Issue by ProudBenzene** [xRyul/obsidian-image-converter#105]
Hello! Your plugin really helps me a lot! Especially the _"Use Markdown links"_ option, as a Typora user too, it really saved me much time.

However, I have a suggestion for the picture editing function. Could you please add a **cropping** option for the picture editor? I think that The demand for picture cropping will not be less than the demand of annotation.

What's more, one more question, After I set up the "Use Markdown links", I found that the links to images are uniformly modified to the _standard link format_ - _relative path_. Is this "_relative path_" not modifiable by default?(I have no intention of using absolute paths or filenames; I just want to ask because I didn't see where to set this option and felt a bit uneasy.)

Last but not least, THX for your dedication!!!

**Comment by xRyul** [comment]
Many thanks! 

Crop/flip/rotate is already implemented, but simply not released yet ❤️⚡Small crop demo:

https://github.com/user-attachments/assets/f7ea6024-52c5-4384-bfe6-9d06239b06fe

As for links, currently, image converter can distinguish between WIKI and MD links. But whether to use shortest, absolute or relative it will go based on Obsidian Settings -> Files and links -> New link format. 

You are the first person who reported to finally use this feature, so I am quite excited 😅

**Comment by ProudBenzene** [comment]
Alright, very much looking forward to the cropping feature being launched!

> As for links, currently, image converter can distinguish between WIKI and MD links. But whether to use shortest, absolute or relative it will go based on Obsidian Settings -> Files and links -> New link format.

Ahhh, _"Use Markdown links"_ function is very important to me, and your plugin is the first plugin with this feature as I know, too😄

and I have a feature request for the _"Use Markdown links"_ too. In my usage scenarios, I always set my link preference to **Wiki&shortest**, to make note citation links in the simplest form. But I'd like the assets links, especially the image links to be set to **Markdown&relevant**, because in Typora and most of other markdown editors, only images with relevant markdown links can be displayed normally.

So instead of following the default settings, I'd like to be able to go a step further and individually choose whether the converted links should be **shortest** or **relevant** in the plugin preference.

Should I open a new issue about the feature request about _"Use Markdown links"_?

**Comment by Moyf** [comment]
I would like to add to this topic - similar to the requirements of @ProudBenzene above, if I want to display the image correctly in other note-taking software (e.g. Typora), it must be an absolute path or a path relative to the current document.

For example:
./Doc.md
./Assets/Pic.png

Then in Doc you have to use ! [](Assets/Pic.png).
Event ![](Pic.png) can not work.

And since I'm using the "shortest path" most of the time in Obsidian, I was wondering if I could just add an extra option for the "use Markdown links" option: always use relative links?

Because I still want to use the shortest link that only has the file name in the whole Obsidian, and only for the image of the md link, I need a relative link.

---

But to be honest, I also rarely edit with external software, so here is just a mention, not very formal FR haha 😄

**Comment by xRyul** [comment]
I've it to my to-do list 🚀 and created a new issue for that request https://github.com/xRyul/obsidian-image-converter/issues/115

As for basic cropping functionality, it is now available from [1.2.13](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.13). 

Many thanks for all your suggestions ❤️
