### ISSUE TITLE
[Bug] Renaming starts to work incorrectly when the conversion is paused

### ISSUE THREAD

**Issue by TonyAtlas** [xRyul/obsidian-image-converter#107]
If I disable image conversion using the “Toggle Image Conversion (Pause/Resume)” command, the image renaming stops following the configured template.

For example, the file should be renamed to: “Scheme-20241129220512409.jpg”

But instead the file is named: “0a34488c899126700b30404aec13ab36_MD5.jpg”.

If I re-enable image conversion, the renaming works correctly again.

OS: Win 10
Obsidian 1.7.7

**Comment by xRyul** [comment]
what is the original filename? 

if you have paused it, then it shouldn't rename or process anything

**Comment by TonyAtlas** [comment]
> what is the original filename?
> 
> if you have paused it, then it shouldn't rename or process anything

Turns out the problem wasn't with your plugin. The renaming was caused by the Local Images Plus plugin. Even though it was turned off, it kept renaming until I reloaded the vault.

But honestly, I thought that when I used the “Toggle Image Conversion (Pause/Resume)” command, the renaming would still work.

I don't fully understand the point of this function then. If I understood correctly, it would be the same as just turning off the plugin.

Is it possible to make it so that when inserting an image not to convert it, but keep the renaming function? Should I create a request on GitHub?

Very often I need such a feature.

**Comment by xRyul** [comment]
Initially it was so that users could assign a shortcut to temporarily
disable the plugin to troubleshoot the past issues. However most of them
are fixed now.

Currently it is there to simply temporarily bypass incompatibility with
other plugins or certain files e.g animated images or certain complex files
with which Image Converter struggles to deal with etc.

Separation of “conversion, compression, resizing” from  “renaming/ output
path” - next release deals with some of this. So hopefully adding command
to pause either of them is not too far also 🤞
