### ISSUE TITLE
[BUG]Right-click menu configuration can affect the right-click menus of other plugins.

### ISSUE THREAD

**Issue by Lamb-Yang** [xRyul/obsidian-image-converter#110]
When the right-click menu configuration option is disabled, it can cause the right-click menus of other plugins to not display properly.

**Comment by xRyul** [comment]
That is strange because if you disable right-click menu in Image Converter, it simply stops execution of the code which renders it.  It doesnt prevent any defaults or propagation etc. 

Which plugin does it break?

**Comment by ObsidianTTRPGProject** [comment]
Multiple reports of it impacting the Second Window plugin. If we disable Image Converter it works instantly again.

**Comment by xRyul** [comment]
What is the use-case for that plugin? How is it being used in TTRPG community? Nowadays there is native Obsidian way of opening image in 2nd window, or am I missing something?

**Comment by Lamb-Yang** [comment]
> That is strange because if you disable right-click menu in Image Converter, it simply stops execution of the code which renders it. It doesnt prevent any defaults or propagation etc.
> 
> Which plugin does it break?

such as `Image Context Menus` plugin

After rolling back to a previous version , they no longer conflict.

**Comment by xRyul** [comment]
Fixed in 1.2.17, although this release is not out yet, as there are a few other things which need fixing.
![Obsidian_yPsQdXZRgn](https://github.com/user-attachments/assets/435c9035-5633-4227-90a2-81fe3c1c4c2a)

I have very limited time with full-time uni, work, family and this plugin in-between. Thus, if you enjoy the project so far, and would like to get certain features faster, to support sleepless nights, please considering supporting via [Ko-fi](https://ko-fi.com/xryul)
