### ISSUE TITLE
Image alignment broken after last update (1.2.16)

### ISSUE THREAD

**Issue by bietiekay** [xRyul/obsidian-image-converter#124]
Apparently now images are aligned out of bounds in my theme (minimal) as well as a quirky animation when I try to use the align feature.

Please make an option so that this can be disabled entirely - it seems to interact with lots of other things regarding the alignment of images.

**Comment by xRyul** [comment]
Hey, it was only one of a few updates which deals with alignment. 

Because of how codemirror works, and considering how complicated it is, I needed to temporarily set some generic CSS classes. These will be patched in future updates. 

Do you know exactly part is exactly gets broken?

For time being if you dont use crop, batch processing or annotation tools -> just comment out or simply delete whole styles.css

Next patch should be out maybe tonight or tomorrow morning.

**Comment by bietiekay** [comment]
Ah I see. So I tried to look into the CSS/HTML but I found that it's too hard to directly make out the difference just from glancing. And my css-kung-fu is not good enough here :)

I will wait for your update, for the time being I have manually reverted to the previous version and will give the next release a try.

Thanks a lot for providing this great tool!

**Comment by xRyul** [comment]
> Same here. The plugin is loaded with Lazy Plugins with 'long' setting so one can easily see this plugin makes the modification. I thought this plugin is triggered on demand. Why would it interfere with the CSS?

That is not how plugins work in Obsidian. And I don't recommend Lazy plugin, as it is known to interfere with functionality of certain plugins. 

In Obsidian, all plugins load during startup. And then if plugin is optimized, its startup will be delayed (Obsidian team calls it "deffered") until layout change. This improves Obsidian load time drastically. 

Only after plugin is loaded, then plugin usually sits in the background listening for various events... like whether you open a new window, open new file, rename, delete file, interact with a note etc. etc. that is why if you have many plugins installed it might also slow down your Obsidian vault.

As for what Image Converter loads after layout-change, you can inspect it in its [onload()](https://github.com/xRyul/obsidian-image-converter/blob/1f8e5dc45f1e1382fbbd356f07de232761a00cda/src/main.ts#L416C1-L416C2) - most of its functionality  is commented out and I think should be self explanatory.

CSS in Image converter is needed for Resizing, Crop/Annotation tool to work, and now it will be needed for Image Alignment and wrapping. 

Because I mainly use vanilla Obsidian, I can't troubleshoot and foresee all incompatibilities with other plugins/themes etc.. thus, if you encounter any issues that Image Converter is breaking, please send me over some screenshot so I could patch it 🙏

**Comment by bietiekay** [comment]
with the 1.2.17 update the behaviour is back to expected/prior. It does not break the alignment now for me. Thanks a lot!

**Comment by xRyul** [comment]
Sorry, I am not sure what I am looking at 😅  do you mean the character in the brackets?
<img width="446" alt="image" src="https://github.com/user-attachments/assets/94a8296b-8426-45a8-84a7-58260709833e" />

How does it supposed to look?

**Comment by xRyul** [comment]
Can it be that the image is smaller than the lines height itself? thus it simply resizes to the top corner as per defaults? 

For example, below 10px is much smaller than lines height, and because when using e.g. drag or scroll-wheel  resizing  we go from bottom right to top left - we go all the the to the corner - so it appears as if it is floating. 
![image](https://github.com/user-attachments/assets/778bf91f-8650-4f3e-af83-f3ae3c676048)
In one of the versions I set resizing to minimum of 50px~, but considering your use-case I might lower it to 20px~ so then it will reduce confusion, and still appear centered. 

![image](https://github.com/user-attachments/assets/997a2bd5-2523-427e-9890-8576bf754ad7)
![image](https://github.com/user-attachments/assets/826a7b2d-77cb-4a4c-b06c-99502f3c52c9)
