### ISSUE TITLE
[Improvement] Cursor after pasting image is behind image

### ISSUE THREAD

**Issue by TimonGisler** [xRyul/obsidian-image-converter#34]
First of all, thanks for this amazing plugin.
Thanks to  the compression, my images are now only a third its size.
And being able to specify a default size is also something that I greatly appreciate (its how I found this plugin at first :D).

Anyway, there is a small inconvenience.
After pasting an image the cursor is now behind the image link.
Which means I have to move my cursor again to the front to continue writing.

Nothing big, but it would improve my quality of life a little bit, if it were possible to fix that. : )

Thanks for your work

Video to demonstrate the inconvenience:

https://github.com/xRyul/obsidian-image-converter/assets/49547606/af572636-c79b-43f7-8439-0a0eae73b30b

**Comment by amogh-w** [comment]
This is happening due to [this](https://github.com/xRyul/obsidian-image-converter/blob/1c2991cc795f59f4f694537d3ac6927b58a82474/src/main.ts#L962C50-L962C50) code.

```
editor.setCursor({ line: currentLine, ch: 0 });
```

After pasting the file and renaming, it places the cursor at the start position. I commented the line and generated a `main.js` file, replaced into my plugins folder and the cursor seems to be fine after pasting.

[main.js.zip](https://github.com/xRyul/obsidian-image-converter/files/13497577/main.js.zip)

I am still learning Obsidian Plugins, so I am not sure what the correct logic should be. Perhaps it should be an easy fix for @xRyul

**Comment by elvarb** [comment]
As many are already used to the current behaviour it would be very beneficial to have this as a setting so people can choose. 

I would personally much more prefer the cursor being at the end of the line as usually you paste an image in and then continue to write. How it is now is probably because some people prefer pasting in images and having the text about the image above it.
