### ISSUE TITLE
[BUG] "| size" doesnt get applied to WIKI links with relative path

### ISSUE THREAD

**Issue by farhansolodev** [xRyul/obsidian-image-converter#35]
When an image link has a path like:
`![[../assets/where which.png]]`
or
`![[../assets/where which.png|300]]` etc. ,
on resizing by dragging the edge of the image, or even when using Shift + Scrollwheel, the link (number part) doesnt get changed to reflect the new sizes.

But when using just the name of the image, it works fine, like:
`![[where which.png]]`
or
`![[where which.png|300]]` etc.

This issue does not exist when copy pasting an image into a note as the name in the link will just have the image's filename, but when manually entering a link with a chord like: `![[whe<Enter>`, it gets changed to `![[../assets/where which.png]]` with an entire filepath, by default, forcing me to manually remove the path so that resizing works.

**Comment by xRyul** [comment]
Fixed in [1.2.0](https://github.com/xRyul/obsidian-image-converter/releases/latest) also related to https://github.com/xRyul/obsidian-image-converter/issues/36


Latest release adds better support for MD and WIKI links. Which in essence also adds better support for relative paths, either with "./" "../" or without. So now it is possible to resize either via drag resize or scrollwheel +mod key 

BTW how did you add ../ to those WIKI links?

**Comment by farhansolodev** [comment]
I either type them in manually or as per my usual workflow, Obsidian auto-inserts it for me as I’ve described. This particular example is from a note inside a folder in the vault.
