### ISSUE TITLE
Resize does not support special characters in image file names

### ISSUE THREAD

**Issue by mimalenke** [xRyul/obsidian-image-converter#4]
Plugin version 1.1.3

If the image file names contains special characters like german umlauts like "Bäume.jpg" and you create a link to the image e.g. "[[Bäume.jpg]]" resizeing the image with dragging the edges replace the image link  with "[[B%C3%A4ume.jpg]]" and you get an error message like "B%C3%A4ume.jpg is not created yet".

Thank you for creating the helpfull plugin.

**Comment by YIRU69** [comment]
The same issue!

**Comment by xRyul** [comment]
Hey, Sorry for getting back to you so late. And many thanks for taking your time to report it! 

I've tested on following examples:

Bäume.jpg
München.png
Schönheit.tif
Köln.webp
Größe.heic

I've also tested with a few special characters from other languages:

French: ` é, è, ê, ë, ç, à, â, ô, û, ù`
Spanish: `á, é, í, ó, ú, ü, ñ`
Chinese: `你, 好`
Japanese: `こんにちは`
Russian: `Привет`

And all seem to be working fine. This will be fixed in the next release. 

Let me know if there are any other characters I could test ;>

**Comment by mimalenke** [comment]
Hi, for the German language that should be all to test. Thank you for working on this!
