### ISSUE TITLE
[FEATURE REQUEST] Canvas support

### ISSUE THREAD

**Issue by ahalvo** [xRyul/obsidian-image-converter#50]
I'm making a pintrest board of some sort in canvas and tried to use the plugin there. When first trying in a normal note it converted into .webp fine but when i copied a image from google and pasted it directly into a canvas it was still a .png.

**Comment by alexgoudemond** [comment]
Hi there, I have the same problem - this feature request would be a great help to me

**Comment by xRyul** [comment]
This should be now fixed in the latest release [1.2.0](https://github.com/xRyul/obsidian-image-converter/releases/tag/1.2.0).

Just FYI, when working on PNG, HEIC or TIFF files - processing might take extra long - and links might take extra time to update. Currently as far as I am aware of there is no Official Obsidian API to interact with Canvases directly, thus there is some visual bug: where images get converted and added in correct place, but for the image cards text to update - we need to either drag the image card or simply refresh the canvas by switching to e.g. another note. 


https://github.com/user-attachments/assets/55a292f6-2a71-4b63-8cc3-431d845086e7

**Comment by alexgoudemond** [comment]
Confirmed working - thank you!
