### ISSUE TITLE
Converting PNG-> WEBP results in larger exported PDF file?

### ISSUE THREAD

**Issue by lowell80** [xRyul/obsidian-image-converter#67]
I'm not 100% sure this is plugin is responsible for what I'm seeing but thought this was a reasonable place to start.

I'm just getting started with Obsidian a few weeks ago, and started using this plugin today.   I was able to reduce a bunch of training slides and reduce my folder of PNG attachments from 24 Mb down to 1.6Mb using the default (WEBP/ 75%) settings in just a few clicks, without any perceivable loss in quality!  Amazing.

I started converting a few more image-heavy notes and wanted to see how the storage reduction translated when exporting to PDF.  But unfortunately, that's resulting in worse behavior.   For example, a note I exported yesterday created a 5 MB PDF file, but after converting all 6 screenshots (again, PNG-> WEBP at 75%), a new PDF export takes 11Mb.  Is this expected behavior?  

Do webp files need to be converted to something less efficient to be stored within a PDF file?  Is there a better format that's supported by PDF export feature that's also supported by this plugin?

**Comment by xRyul** [comment]
Image Converter simply converts the image, and it is reflected in its output file (which indeed gets smaller). But what happens afterwards is beyond capabilities of this plugin. 

Probably related to PDF.js itself not supporting WEBP,  thus if that library doesn't support it then Obsidian won't either.  Because no WEBP supported, then it probably converts it back into PNG just to keep transparency, thus resulting in larger file size. Although, I might be wrong. It might be also related to how Obsidian itself deals with raster images when it exports them as PDFs. Obsidian PDF export is very basic, all is done "automagically" in the background, but what is actually being done to text , color images, b&w images etc we don't know.  Obsidian doesn't support downsampling of images, nor compression, nor quality or ppi settings. 

Hopefully when annotation of PDFs comes officially to Obsidian ([roadmap](https://obsidian.md/roadmap/)) then it might also fix this file size issue too.

**Comment by lowell80** [comment]
I appreciate your plugin and taking the time to respond.  Thanks!

I've played a bit with Stirling PDF with mixed results, smaller PDFs, but sometimes they were broken.  Anyway, none of it is a deal breaker. Thanks again!
