### ISSUE TITLE
[FEATURE REQUEST] Skip if the compressed image size is larger than the original

### ISSUE THREAD

**Issue by muratagawa** [xRyul/obsidian-image-converter#83]
When images are compressed using this plug-in, the image size may be larger than before compression. For such cases, I would like an option to use the image as it was before compression.

**Comment by xRyul** [comment]
So far I found  only 1 case when image would get bigger, is when dealing with mobile image formats. It was the main reason why I implemented a new "Summary" notification, to see the difference in file size before/after conversion. 

What was your use case if not a secret? What kind of image were you trying to process?

**Comment by muratagawa** [comment]
[image.zip](https://github.com/user-attachments/files/17655163/image.zip)


If an image is already well compressed, such as an AVIF formatted image, the size of the image will increase when it is compressed by a plug-in.

For example, in the image above, the original file size is 20KB, but after compression by the plug-in, the file size expands to 36KB. (Default plug-in settings. Format = WebP, Quality = 75)

In such cases, the original image should be attached as is.

**Comment by muratagawa** [comment]
Closed by mistake... Reopened 🤤

**Comment by xRyul** [comment]
I've played around with it a little and added a small new toggle. Basically it will do some calculations in memory and select the output to be with the smallest file size while still keeping target format (instead of defaulting back to original). It is a little convoluted, I think the best is to simply test it in practice. 

<img width="715" alt="image" src="https://github.com/user-attachments/assets/34bc0427-30b0-435d-a4ae-e3a0c173d7f4">

**Comment by xRyul** [comment]
Hey @HypedLama conversion of SVGs will heavily depend on its content, it is conversion of vector into raster image, hence why irregularity in file-size. If you would like me to look into it further, please open a new issue, and include a sample svg file. 

I am closing this now, as the main functionality is already there.
