### ISSUE TITLE
If one note is open in two devices that are in sync ...

### ISSUE THREAD

**Issue by Dopairym** [xRyul/obsidian-image-converter#85]
If one note is open in two devices that are in sync ( I'm using syncthing ) and then if i insert an image in one of the devices while the note is also open in the other devise the first devise will rename it and also the second devise will try to sync it and this brake the file ( in my case i insert and gif the first device renames it and it stays with .gif but when the image gets synced into the second device it changes gif to png )

**Comment by garugc** [comment]
since the last update i also have chaos everywhere. Several graphics have disappeared completely at random. Then I restored them from the trash can. But as soon as I open obsidian on my phone and it synchronizes (with Remotely safe), Image Converter processes several graphics again (even though they were already processed on the PC) and chaos ensues again. The graphics in the Notes are deleted again. I have entered the same path for new graphics in Image Converter on the PC and the cell phone. But this is not about new graphics but about graphics that have already been saved. I have now spent an hour checking all the Notes because I am afraid of losing data.

**Comment by garugc** [comment]
There were never any problems before, only now after the update. I suspect that Image Converter identifies the synchronized images as newly imported files at the very moment when the synchronization process is still in progress. This creates a conflict because Image Converter or Obsidian renames the file and the link to the image in the note is changed as a result. I am not a programmer and do not know how the processes at Remotely Safe work. But since I don't want to do without it, I unfortunately have to deactivate Image Converter.

**Comment by garugc** [comment]
Ok, I see, there is the option "If an output file already exists".. and that's why I always had the images with an additional “-1” in the folder and the links in the Notes were no longer correct. Probably because Remotely safe synchronized the changed file directly. I don´t know..

**Comment by Dopairym** [comment]
This will be also great feature to add i mean like a toggleable function ao
it renames all the attachments
https://github.com/xRyul/obsidian-image-converter/issues/84

**Comment by xRyul** [comment]
> There were never any problems before, only now after the update. I suspect that Image Converter identifies the synchronized images as newly imported files at the very moment when the synchronization process is still in progress. This creates a conflict because Image Converter or Obsidian renames the file and the link to the image in the note is changed as a result. I am not a programmer and do not know how the processes at Remotely Safe work. But since I don't want to do without it, I unfortunately have to deactivate Image Converter.

I am trying to look into it. 

Could you test following and see if issue still persists:
[image-converter-1.2.3.zip](https://github.com/user-attachments/files/17681250/image-converter-1.2.3.zip)

**Comment by xRyul** [comment]
@Dopairym and @garugc please update to the [latest](https://github.com/xRyul/obsidian-image-converter/releases/latest) release and see if it fixes this issue 🤞

**Comment by garugc** [comment]
Yes, it works. Thank you very much!!
